#!/bin/sh
#
# (c) https://github.com/MontiCore/monticore
#
# This tool downloads the Gradle 7.6.4 wrapper
#


BASEDIR=$(dirname $0)
mkdir -p $BASEDIR/gradle/wrapper
wget -O $BASEDIR/gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/refs/tags/v7.6.4/gradle/wrapper/gradle-wrapper.jar
wget -O $BASEDIR/gradlew https://raw.githubusercontent.com/gradle/gradle/refs/tags/v7.6.4/gradlew
wget -O $BASEDIR/gradlew.bat https://raw.githubusercontent.com/gradle/gradle/refs/tags/v7.6.4/gradlew.bat

echo """distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.4-bin.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
""" > $BASEDIR/gradle/wrapper/gradle-wrapper.properties